### ISSUE TITLE
Safari/Chrome: Drag and Drop UX when replacing HTML, CSS or JS within the container

### ISSUE THREAD

**Issue by sarah-braumiller** [paceaux/McSandy--the-HTML5-offline-Sandbox#23]
When user drags one HTML (or CSS/JS) file into the HTML container, the user cannot replace the original file by just dragging/dropping a secondary/updated file. The secondary file gets added to the first dragged/drop HTML.

If the user wanted to replace the first HTML with a brand new HTML file-- they would have to cmmd+a (select all) and delete, and THEN drag and drop the new HTML over.

**Comment by paceaux** [comment]
this has been resolved in latest big dev build. user can drag the labels
