### ISSUE TITLE
Delete doesn't fully delete the sbx

### ISSUE THREAD

**Issue by sarah-braumiller** [paceaux/McSandy--the-HTML5-offline-Sandbox#26]
If the user puts some code into the HTML, and then, under "This Sandbox", name it and click save.

At this point, it shows up under the "Other Sandboxes" dropdown menu. 

However, when I delete the sandbox out of "This Sandbox", while it removes it from the dropdown, the sandbox still exists if the user knows/knew the url (http://mcsandy.com/#test)

**Comment by paceaux** [comment]
delete has been fixed.
